CREATE TABLE IF NOT EXISTS topics(
slug VARCHAR PRIMARY KEY AUTOINCREMENT,
DESCRIPTION VARCHAR
)

CREATE TABLE IF NOT EXISTS users(
username VARCHAR PRIMARY KEY AUTOINCREMENT,
name VARCHAR not NULL,
avatar_url VARCHAR
)

CREATE TABLE IF NOT EXISTS articles(
articleId VARCHAR PRIMARY KEY AUTOINCREMENT,
title VARCHAR NOT NULL,
topic VARCHAR NOT NULL REFERENCES topics(slug),
author VARCHAR NOT NULL REFERENCES users(username),
body VARCHAR NOT NULL,
createdAt TIMESTAMP DEFAULT NOW(),
VOTES INT DEFAULT 0 NOT NULL,
articleImgUrl VARCHAR Default
)

CREATE TABLE IF NOT EXISTS COMMENTS(
commentId VARCHAR PRIMARY KEY AUTOINCREMENT,
body VARCHAR NOT NULL
articleId Int REFERENCES articles(articleId) NOT NULL,
author VARCHAR NOT NULL REFERENCES users(username),
VOTES INT DEFAULT 0 NOT NULL,
createdAt TIMESTAMP DEFAULT NOW(),
)